apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "beanstalkd.fullname" . }}
  labels:
    app: {{ template "beanstalkd.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ template "beanstalkd.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "beanstalkd.fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
  template:
    metadata:
      labels:
        app: {{ template "beanstalkd.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '{{ .Values.metrics.port }}'
      {{- end }}
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.AntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app: {{ template "beanstalkd.fullname" . }}
                release: {{ .Release.Name | quote }}
        {{- else if eq .Values.AntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: {{ template "beanstalkd.fullname" . }}
                  release: {{ .Release.Name | quote }}
        {{- end }}
      containers:
      - name: {{ template "beanstalkd.fullname" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        args:
        - -z {{ .Values.beanstalkd.maxJobSize }}
        ports:
        - name: beanstalkd
          containerPort: 11300
        livenessProbe:
          tcpSocket:
            port: beanstalkd
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: beanstalkd
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: binlog
          mountPath: /var/lib/beanstalkd
      {{- if .Values.metrics.enabled }}
      - name: {{ template "beanstalkd.fullname" . }}-metrics
        image: {{ .Values.metrics.image }}
        imagePullPolicy: {{ .Values.metrics.imagePullPolicy }}
        args:
        - --web.listen-address=:11301
        - --beanstalkd.address={{ template "beanstalkd.fullname" . }}:{{ .Values.service.port }}
        ports:
        - name: metrics
          containerPort: 11301
      {{- end }}
      volumes:
      - name: binlog
        persistentVolumeCliaim:
          claimName: {{ template "beanstalkd.fullname" . }}
