name: beanstalkd
version: 1.1.0
appVersion: "1.10"
description: Beanstalk is a simple, fast work queue.
keywords:
- beanstalkd
- queue
- prometheus
- metrics
home: http://kr.github.io/beanstalkd/
sources:
- https://github.com/davidtannock/docker-beanstalkd
- https://github.com/davidtannock/beanstalkd_exporter
maintainers:
- name: David Tannock
engine: gotpl
